import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { LuArrowRight, LuSparkles, LuTarget, LuBrain, LuTrendingUp, LuBookOpen, LuUsers, LuZap, LuX, LuGraduationCap, LuUser } from 'react-icons/lu';
import { useAuth } from '../context/AuthContext';
import './Landing.css';

export default function Landing() {
  const vantaRef = useRef(null);
  const vantaEffect = useRef(null);
  const [showAuthModal, setShowAuthModal] = useState(false);
  const [authTab, setAuthTab] = useState('login');
  const [selectedRole, setSelectedRole] = useState(null);
  const { login, register, error } = useAuth();

  const openAuthModal = (tab) => {
    setAuthTab(tab);
    setShowAuthModal(true);
  };

  const closeAuthModal = () => {
    setShowAuthModal(false);
  };

  useEffect(() => {
    // Initialize Vanta Globe
    const initVanta = () => {
      if (window.VANTA && vantaRef.current && !vantaEffect.current) {
        vantaEffect.current = window.VANTA.GLOBE({
          el: vantaRef.current,
          mouseControls: true,
          touchControls: true,
          gyroControls: false,
          minHeight: 200.00,
          minWidth: 200.00,
          scale: 1.00,
          scaleMobile: 1.00,
          color: 0xd43e48,
          color2: 0x1a1a2e,
          backgroundColor: 0x0a0a0f,
          size: 1.2,
        });
      }
    };

    // Try immediately, or wait for scripts to load
    if (window.VANTA) {
      initVanta();
    } else {
      const timer = setInterval(() => {
        if (window.VANTA) {
          initVanta();
          clearInterval(timer);
        }
      }, 200);

      return () => clearInterval(timer);
    }

    return () => {
      if (vantaEffect.current) {
        vantaEffect.current.destroy();
        vantaEffect.current = null;
      }
    };
  }, []);

  const features = [
    { icon: <LuTarget />, title: 'Adaptive Quizzes', desc: 'AI-driven difficulty adjustment that adapts to your skill level in real-time.' },
    { icon: <LuBrain />, title: 'AI-Powered Insights', desc: 'Get personalized explanations and custom study paths generated by AI.' },
    { icon: <LuTrendingUp />, title: 'Smart Analytics', desc: 'Detailed dashboards with performance trends and weak area detection.' },
    { icon: <LuBookOpen />, title: 'Curated Resources', desc: 'Hand-picked video, article, and practice recommendations for each topic.' },
    { icon: <LuUsers />, title: 'Educator Dashboard', desc: 'Class-wide heatmaps, per-student drill-down, and quiz management.' },
    { icon: <LuZap />, title: 'Gamification', desc: 'Earn XP, unlock badges, maintain streaks, and climb the leaderboard.' },
  ];

  return (
    <div className="landing">
      {/* Hero Section with Vanta Globe */}
      <section className="hero" ref={vantaRef}>
        <div className="hero-overlay"></div>
        
        <nav className="landing-nav">
          <div className="landing-nav-logo">
            <div className="logo-icon-landing">🧠</div>
            <span className="logo-text-landing">IntelearnX</span>
          </div>
          <div className="landing-nav-actions">
            <button className="btn btn-secondary" id="nav-login-btn" onClick={() => openAuthModal('login')}>Sign In</button>
            <button className="btn btn-primary" id="nav-register-btn" onClick={() => openAuthModal('register')}>Get Started</button>
          </div>
        </nav>

        <div className="hero-content animate-fadeInUp">
          <div className="hero-badge">
            <LuSparkles />
            <span>AI-Powered Personalized Learning</span>
          </div>
          <h1 className="hero-title">
            Learn Smarter,<br />
            <span className="hero-gradient-text">Not Harder</span>
          </h1>
          <p className="hero-subtitle">
            IntelearnX adapts to your unique learning style. Take adaptive quizzes, 
            discover your weak areas, and get AI-generated study paths — all in one platform.
          </p>
          <div className="hero-actions">
            <button className="btn btn-primary btn-lg" id="hero-get-started" onClick={() => openAuthModal('register')}>
              Start Learning Free
              <LuArrowRight />
            </button>
            <button className="btn btn-secondary btn-lg" id="hero-login" onClick={() => openAuthModal('login')}>
              Sign In
            </button>
          </div>

          <div className="hero-stats">
            <div className="hero-stat">
              <span className="hero-stat-value">80+</span>
              <span className="hero-stat-label">Quiz Questions</span>
            </div>
            <div className="hero-stat-divider"></div>
            <div className="hero-stat">
              <span className="hero-stat-value">4</span>
              <span className="hero-stat-label">Subjects</span>
            </div>
            <div className="hero-stat-divider"></div>
            <div className="hero-stat">
              <span className="hero-stat-value">AI</span>
              <span className="hero-stat-label">Powered</span>
            </div>
            <div className="hero-stat-divider"></div>
            <div className="hero-stat">
              <span className="hero-stat-value">∞</span>
              <span className="hero-stat-label">Adaptive</span>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="features-section" id="features">
        <div className="container">
          <div className="section-header animate-fadeInUp">
            <span className="section-badge">Features</span>
            <h2 className="section-title">Everything You Need to <span className="gradient-text">Excel</span></h2>
            <p className="section-subtitle">Our AI-driven platform combines adaptive testing, intelligent analytics, and personalized recommendations.</p>
          </div>

          <div className="features-grid">
            {features.map((feature, index) => (
              <div className="feature-card animate-fadeInUp" key={index} style={{ animationDelay: `${index * 0.1}s` }}>
                <div className="feature-icon">{feature.icon}</div>
                <h3 className="feature-title">{feature.title}</h3>
                <p className="feature-desc">{feature.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="how-section">
        <div className="container">
          <div className="section-header">
            <span className="section-badge">How It Works</span>
            <h2 className="section-title">Three Steps to <span className="gradient-text">Mastery</span></h2>
          </div>
          <div className="steps-grid">
            <div className="step-card animate-fadeInUp delay-1">
              <div className="step-number">01</div>
              <h3>Choose Your Subject</h3>
              <p>Pick from Mathematics, Science, Computer Science, or English. Select your topic and difficulty.</p>
            </div>
            <div className="step-card animate-fadeInUp delay-2">
              <div className="step-number">02</div>
              <h3>Take Adaptive Quizzes</h3>
              <p>Our AI adjusts question difficulty in real-time based on your performance. Get instant feedback.</p>
            </div>
            <div className="step-card animate-fadeInUp delay-3">
              <div className="step-number">03</div>
              <h3>Get AI Recommendations</h3>
              <p>Receive personalized study paths, resource recommendations, and track your progress over time.</p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="cta-section">
        <div className="container">
          <div className="cta-card">
            <div className="cta-content">
              <h2>Ready to Transform Your Learning?</h2>
              <p>Join IntelearnX today and experience AI-powered personalized education.</p>
              <button className="btn btn-primary btn-lg" id="cta-register" onClick={() => openAuthModal('register')}>
                Get Started Now <LuArrowRight />
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="landing-footer">
        <div className="container">
          <div className="footer-content">
            <div className="footer-brand">
              <div className="landing-nav-logo">
                <div className="logo-icon-landing">🧠</div>
                <span className="logo-text-landing">IntelearnX</span>
              </div>
              <p>AI-Powered Personalized Learning Pathways</p>
              
            </div>
            <div className="footer-links">
              <div>
                <h4>Platform</h4>
                <button onClick={() => openAuthModal('register')}>Get Started</button>
                <button onClick={() => openAuthModal('login')}>Sign In</button>
              </div>
              <div>
                <h4>Features</h4>
                <span>Adaptive Quizzes</span>
                <span>AI Insights</span>
                <span>Analytics</span>
              </div>
            </div>
          </div>
          <div className="footer-bottom">
            <p>© 2026 IntelearnX. Built for hackathon by Team IntelearnX.</p>
          </div>
        </div>
      </footer>

      {/* Glass Morphism Auth Modal */}
      {showAuthModal && (
        <div className="auth-modal-overlay" onClick={closeAuthModal}>
          <div className="auth-modal" onClick={(e) => e.stopPropagation()}>
            <button className="auth-modal-close" onClick={closeAuthModal}>
              <LuX />
            </button>
            <div className="auth-modal-tabs">
              <button 
                className={`auth-tab ${authTab === 'login' ? 'active' : ''}`}
                onClick={() => setAuthTab('login')}
              >
                Sign In
              </button>
              <button 
                className={`auth-tab ${authTab === 'register' ? 'active' : ''}`}
                onClick={() => setAuthTab('register')}
              >
                Sign Up
              </button>
            </div>
            
            {!selectedRole ? (
              <div className="role-selection">
                <h3>Choose your role</h3>
                <p className="role-subtitle">Select how you want to use IntelearnX</p>
                <div className="role-buttons">
                  <button 
                    className="role-btn"
                    onClick={() => setSelectedRole('student')}
                  >
                    <LuGraduationCap className="role-icon" />
                    <span>Student</span>
                    <p className="role-desc">Take quizzes, track progress, and learn AI-powered study paths</p>
                  </button>
                  <button 
                    className="role-btn"
                    onClick={() => setSelectedRole('educator')}
                  >
                    <LuUser className="role-icon" />
                    <span>Teacher</span>
                    <p className="role-desc">Create quizzes, view analytics, and manage your classroom</p>
                  </button>
                </div>
              </div>
            ) : (
              <div className="auth-modal-content">
                <button className="back-role-btn" onClick={() => setSelectedRole(null)}>
                  ← Back to role selection
                </button>
                {error && <div className="auth-error" style={{ color: '#ff6b6b', background: 'rgba(255, 107, 107, 0.1)', padding: '10px', borderRadius: '8px', marginBottom: '15px', textAlign: 'center', fontSize: '0.9rem' }}>{error}</div>}
                {authTab === 'login' ? (
                  <form className="auth-form" onSubmit={async (e) => { 
                    e.preventDefault(); 
                    const form = e.target;
                    const email = form.email.value;
                    const password = form.password.value;
                    const success = await login(email, password);
                    if (success) {
                      closeAuthModal();
                    }
                  }}>
                    <div className="form-group">
                      <label>Email</label>
                      <input name="email" type="email" placeholder="Enter your email" required />
                    </div>
                    <div className="form-group">
                      <label>Password</label>
                      <input name="password" type="password" placeholder="Enter your password" required />
                    </div>
                    <button type="submit" className="btn btn-primary btn-full">
                      Sign In as {selectedRole === 'student' ? 'Student' : 'Teacher'}
                    </button>
                  </form>
                ) : (
                  <form className="auth-form" onSubmit={async (e) => { 
                    e.preventDefault(); 
                    const form = e.target;
                    const userData = {
                      name: form.name.value,
                      email: form.email.value,
                      password: form.password.value,
                      role: selectedRole,
                    };
                    const success = await register(userData);
                    if (success) {
                      closeAuthModal();
                    }
                  }}>
                    <div className="form-group">
                      <label>Full Name</label>
                      <input name="name" type="text" placeholder="Enter your name" required />
                    </div>
                    <div className="form-group">
                      <label>Email</label>
                      <input name="email" type="email" placeholder="Enter your email" required />
                    </div>
                    <div className="form-group">
                      <label>Password</label>
                      <input name="password" type="password" placeholder="Create a password" required />
                    </div>
                    <button type="submit" className="btn btn-primary btn-full">
                      Create {selectedRole === 'student' ? 'Student' : 'Teacher'} Account
                    </button>
                  </form>
                )}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
